workflows:
  default-workflow:
    environment:
      xcode: latest
      cocoapods: default
      vars:
        GODOT_VERSION: 3.5
        GODOT_EXEC_URL: https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_osx.universal.zip
        GODOT_TEMPLATES_URL: https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
        GODOT_TEMPLATES_DIR: "/Users/builder/Library/Application Support/Godot/templates"
        GODOT_EXEC: Godot.app/Contents/MacOS/Godot

        APP_STORE_CONNECT_ISSUER_ID: f73c523e-7e17-491f-9f26-70cf6687c732
        APP_STORE_CONNECT_KEY_IDENTIFIER: 5V23RW6D4B
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmk3eTZhRXNJa0lQYldoQzdacDktZlI2dXpZbGROT3BZZ1AzcUkyR1VnS0V6R3h6aEY0Xy1lZUo2MmJkYWg3MlFpWVIxcEFoYWRxRHpBeGs0c0pVdmVDYTdHZ3dsa2lDNVEzNGlpM2RrS0U2RnlYY0xCMHVnb3gzZEllQUstRXNGYWhVLUpmMlFzMTExaktqRXZ4enRfNFVGU2Jqb3FYZTBKWXdudENYR0V5dUxKM0p5bUZBbk81dVY3TzN1eHJGakV3MnI5WGZDemxTSDNORTJzU1VaaklyUU1HcmJXc2dXSE9mcXU2Z0N1TFdRS1hIOC1hb0Rtb0RJR0hMTnE5Vk5BcmVMNDg2YUJURGxkdjNXeVlkdGFmYkI5YlZ2VEF2WU9OWTlvQjY0QjRRTUJlZTNNQzh3UmQ2clJJMnVPMDdZLWRPcWR5Y083MGFjNkVZMGpkcThqVExjenF2NzN4V2h0ekt1SzRHR1pRMUVjcHFyZ1dGV1JUTlBjVm53a2VvaGdMRmM4LWZYWWMtaGpJa2hrRDNOWVhJQkMyY2RHd3hYVlVkWG5OdzZ3SktCMzJiND0=)
        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmk3eTZhUlROTGY1bm5rWmk3MVVKZEk2SGhBaW54NHpVRDUza1NGSHRFelJwQTN6R2o2U2I5Wk5HemxoZVp6NC02WFhIUlZrTGhIb0d6TC1iQVpiWXk0dzZrcTA2TnFsT1JHY0NHWUVCRXdNVUVTdjJoOVp1S0JHS2h0aE43VnhMeDkwQzYyNXM0TEhHb3hSOGdLcTdUdDU5MkNlRWRkWTdtYjBQaXpOdEdjUkxQWHVjZzVvYTQ3S1g4SV9FYnJ4eWpiWFY4LXdZY3FyMzZ6RlpCSFFscnROYXRHZzNrRkppLTRiSDZLcDRkeDkwbHlJR3lkZXpFNHJELWZtRFFMWXFLY2xYejZtMUdqcDk3LXl6SElOem92WXRsVS1aamFiaEJlNU82blZZMHo5dFhoNlNMUEJLLXpHYkhtMFJfV1hMV3RNMXVpY0pBWnBSWlRMRDJzT1pOdWJIZlY2SDRnMUIzczVFOEhWLV8temtrZ3Y5WHlCWHRuQkE1X3l0ZTZGNkNLVWRxUWVzXzdPa056aC1zS1Q4N2xTWlA3LUQ3alJhYXJid29iMGk3RXhfdzRaX0MxMzgya1ZfaGY1VzRqUGpaX2E1NmF0dnpLbTc2d05UaGNGd0Q0bjlEX1oxUFUzWldPNkRNX1FTemo2YnhmSVgxM0lSSFBNWjdOWjM5Z2Vxa2tLRldmekh3TG5hZzM5cXp4bU5mMmZaWFB4SmI4N3k5Q2pVZHYwYnlsMDdCU0lJZzNpUEUyT1ZXa0VUaEtkbm5relJTbVlMclJMUmh6bm5Ldi1lWElKdE8yWnB2YTBZTndpRlM1MkdEbWd0REZZNlU3eTcxaE5PbVBaOVdiakpjYTYzVzM1QkJqWWVkNGg3dU1pdU81Z3FTdnk5VU9sWGdQZ0h0ZnJkV1lVTWlMWWcxSDdJTFlOTTdVMGpONGRlNGxrTzNJUk9pLUZqaFhUYXJ4Nl9qWEstbGJXVDlkTTdJemhiWW5rd3k5bnFjWFQwOUkxamljT3A2NUtIS0hNVnpldjF6ZGVCblpvbThzbEljZlNGWFYteV9aTlhRY0diWEVqajVHam11V1Fnc1MxVm93X0RyekU5VXMwVTZhM2tUWGtIRnZmbTRCckxiZWVKUHlYbEUwT21pX2o4WnAxRzJZWlhGUlZ3Z0R6Z3Jrb05jWVBsaG5EVVBsX284VkJEbXFuWDMwcXdRaE5WOWF4VWpSN2dqWF9uT19JLXktTVlRNDVFTm9fTFlyZFp2aGdNRndIV1gwazZHb3F5azMxejZ6eGlyLTQtUWxhTW10Z0dvNmdfQVdueVpFMzYydGhNd096aENlXy1QLVFnSnBPaWlZZUJSYXhQX0N3dTZpbWRIcGtCai16ZjhEQmtsTmtXMTJDSWpEYXRvTUlVOXE4LWNKWkkwMWhXeDVjTGRnak9pUDlMMm9sbm5XNUR5OXptbjlPZkJBOHVqNlVYMnAwRVRobEJLbTNJR0djOFhUS2ZCa1VRVEZFU0N0bFNDZ3RHRmo1U0gzdXZKcVQtSlRoRlBfamIzZWx1bWpYeUlRd0l4VHJGQ3o5UG9aV1ZLZ2hFLWRpVV93QXhYQXA0VGpqNG1xX2UwT3M5S0YybkthX0V0SV9MVjVvbDhQbWF5M3NXVldzWEFGSFU0eWZXVV9oVXItZzJqMlpkYVJXUmg0anNMX2RnZExMd21pYnJMTllsSG41VFhxa0Rpc2NFdXRHdU9wdW1qLWFYS2lJZlJLTHFfYmZmSXRiaEd4ME9QNjVvYXhlWktFNzZ4R0l6VXlqb0xObTNhT0gyN1FWYXdUY0FiOE5icHM1SGl4eGlHOTEzMGlmRUg3RTQ0dGp3dEpKSkJ0aWFYeEpZQ0Vrd0dyRW9ZaENsWVJHOUg0NzNjX0puMjJMR1B6M0ExUTRXN0RPTzAyTmZGV2hIQUl4YjVRR1RiVUZuQnNKLTBXNG5PdjFpZVFobngyeWh5M3J6OE5YaFFnekJkU1ZaYlhndEJVTHRvUGxMNG5GX1VmV29SelFVRGFIVzNja3NTNDgybGlqWUF5b2lsbWVaV2stN2FMNy1NVnRwU0N6V1cxSlY5TFF0VXFJVGpMT1dWXzQzRTZqeXkxUW4xdFA0QnpjTlp4S2ZXeEw3d3NQaU84TklQbHpma25FVVpWYVAyaW1sWEV6TDNvNmtaaDg1OF9CYUNfZ3UzbW1GMWlPWU9Fdm1LSjhUdGlLUWpub3VEVkRKbWdXbmgzM0h2WjlNNnI0S0FBeWt1bTVMMUJqbGNWdi1hclhxUXFKbWtoa1YzNDN1aDdBWmZVajN2Qi05SjZCWC1LTTQ5RHVxYmF4N3hGdmE5QXVwcVYwbzVTQkUzTkFrV3pudG9WazJHY1o4dVoyc3lxMEpuSzJYT2wwUERHeWU5UUV2Q3lZVE1TUXkwQVFSZVFVdW5PTUVhc0dLR2I1dDR0WGxyUVJzaExNWldQbXRKamhyZHJzV2ZQbHJISml3X1E1cWVJQUFxWjJlYzhXbXlHLXFJNUhueHRvdjdIX0pFWDd5OG5PVzNXRDJCck1BWGhMUU1EQ2VwUUY3WXI5eXB2T2pxRGk0aTlaaEVSd3hhOV9Ld054Q0toS1JCNVIzOFVnUktUS0V2MldrX3lYdFZhMmZISHp3R0dOa2ZBZUtXYnNXdXB6Vk5NTnNNdEFnRmhwdWRxVWJXTjZCYXJ6TmQ1YXNDS202elBPeWF3OVFsX2I2dlVPVE5IOTZwUnNvYm9aY3hkcW42QlRvMEp1Qk41NFhYaXRpQ2phbGs1eUtSbmlDMUhiZnJXX1VyRjVObXNIUWkzQnZkT1hUQ1ZvNGxyRzZKUGYtWC16NUMwOUlSQlF0MjVhM00ycWdpb1V3VVF6WGFzeVp0aTdEZUw3ZGhqdVpsZHpqcXFicWRuV3U5WXZnOHR1WGNMY29uSF9fdDBvZWxteXhNeTY4Q0g5cWItcm9CbWROaFFUdHpsVElrdUVUUUV2RnNMYU9sSFJzTHdoVVBoMjZVLTFqNldQNDVQdlJGT2lIbFkyS2RBeUxqRnVNdmJEMU9KVHBTeUJnY1pqaEVxS2pR)
    cache:
      cache_paths:
        - $GODOT_TEMPLATES_DIR
    scripts:
      - name: Download Godot engine
        script: |
                      curl -o ./godot.zip ${GODOT_EXEC_URL} && unzip ./godot.zip
      - name: Download Godot templates
        script: |
                      if [ ! -f "${GODOT_TEMPLATES_DIR}/${GODOT_VERSION}.stable" ]; then
                      curl -o ./godot-templates.zip ${GODOT_TEMPLATES_URL} && unzip ./godot-templates.zip
                      mkdir -p "${GODOT_TEMPLATES_DIR}" && mv templates "${GODOT_TEMPLATES_DIR}/${GODOT_VERSION}.stable"
                      fi
      - name: Export project
        script: |
                      mkdir builds/
                      ${GODOT_EXEC} --path . --no-window --export iOS builds/xcode
      - name: Setup codesign
        script: |
                      keychain initialize
                      app-store-connect fetch-signing-files "games.hclcat.card0" --type IOS_APP_STORE --create
                      keychain add-certificates
                      xcode-project use-profiles
      - name: Build .ipa
        script: |
                      xcode-project build-ipa --project "builds/xcode/Card0.xcodeproj" --scheme "Card0"
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM


